<?php
/**
 * Created by PhpStorm.
 * User: tag19
 * Date: 01.05.2019
 * Time: 3:30 PM
 */

namespace app\models;


use yii\db\ActiveRecord;

class Contributors extends ActiveRecord
{
    public static function tableName()
    {
        return 'Contributors';
    }

    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['name'], 'safe'],
            [['role_id'], 'integer'],
            [['project_id'], 'integer'],
        ];

    }
    public function getProject() {
        return $this->hasOne(Project::className(), ['id'=>'project_id']);
    }
//    public function setStartDate($date) {
//        $this->start_date = $date;
//    }
    public function setProjectId($id) {
        $this->project_id = $id;
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}