<?php
/**
 * Created by PhpStorm.
 * User: tag19
 * Date: 02.04.2019
 * Time: 9:33 PM
 */

namespace app\models;


use Yii;
use yii\data\ActiveDataProvider;

class ProjectSearch extends Project
{
    public function rules() {
        return  [
            //[['id'], 'integer'],
            [['name', 'project_image', 'user_id'], 'safe'],
        ];
    }
    public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($params) {
        $query = Project::findBySql("SELECT * FROM Projects WHERE user_id=". Yii::$app->user->identity->getId());

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            return $dataProvider;
        }

        $query->andFilterWhere([
            //'id' => $this->getAttribute('id'),
            'name' => $this->getAttribute('name'),
            'project_image' => $this->getAttribute('project_image'),
            'user_id' => $this->getAttribute('user_id')
        ]);

        return $dataProvider;
    }
}