<?php
/**
 * Created by PhpStorm.
 * User: tag19
 * Date: 19.03.2019
 * Time: 11:37 PM
 */

namespace app\models;

use yii\db\ActiveRecord;

class Project extends ActiveRecord
{
    public static function tableName()
    {
        return 'Projects';
    }

    public function rules() {
        return [
            [['id'], 'required'],
            [['name'], 'string'],
            [['project_image'], 'string'],
        ];
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}